<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-android35.0</TargetFramework>
    <SupportedOSPlatformVersion>26.0</SupportedOSPlatformVersion>
    <JunimoGateRequiresSmapi>true</JunimoGateRequiresSmapi>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Lib.Harmony" Version="2.4.2-junimogate.64" />
    <PackageReference Include="MonoGame.Framework.Android" Version="1.0.0-junimogate.f5d8bf.4" />
    <Reference Include="StardewValley">
      <HintPath>$(JunimoGateGameReferenceDir)/StardewValley.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <ProjectReference Include="../JunimoGate.Core/JunimoGate.Core.csproj" />
    <ProjectReference Include="../JunimoGate.Android/JunimoGate.Android.csproj" />
    <ProjectReference Include="../JunimoGate.Extraction/JunimoGate.Extraction.csproj" />
    <ProjectReference Include="../JunimoGate.Mods/JunimoGate.Mods.csproj" />
    <ProjectReference Include="../JunimoGate.Rewriter/JunimoGate.Rewriter.csproj" />
    <ProjectReference Include="../../smapi/src/SMAPI/SMAPI.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AndroidNativeLibrary Include="../../artifacts/native-cacheflush/libjunimogate-cacheflush.so">
      <Link>lib/arm64-v8a/libjunimogate-cacheflush.so</Link>
    </AndroidNativeLibrary>
  </ItemGroup>
</Project>
