<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Shared/TestHarness.cs" Link="TestHarness.cs" />
    <Compile Include="../../smapi/src/SMAPI/Framework/ModLoading/ModAssemblyBindingPlanner.cs"
             Link="SMAPI/ModAssemblyBindingPlanner.cs" />
    <Compile Include="../../smapi/src/SMAPI/Framework/ModLoading/CustomAttributeTypeScopeRewriter.cs"
             Link="SMAPI/CustomAttributeTypeScopeRewriter.cs" />
    <Compile Include="../../smapi/src/SMAPI/Framework/ModLoading/TypeDefinitionVisibility.cs"
             Link="SMAPI/TypeDefinitionVisibility.cs" />
    <Compile Include="../../smapi/src/SMAPI.Internal/ConsoleWriting/ConsoleLogLevel.cs"
             Link="SMAPI/ConsoleLogLevel.cs" />
    <Compile Include="../../smapi/src/SMAPI/Mobile/AndroidLoadingLogBuffer.cs"
             Link="SMAPI/AndroidLoadingLogBuffer.cs" />
    <Compile Include="../../smapi/src/SMAPI/Mobile/AndroidBackgroundTaskTracker.cs"
             Link="SMAPI/AndroidBackgroundTaskTracker.cs" />
    <PackageReference Include="Mono.Cecil" Version="[0.11.6]" />
    <ProjectReference Include="../../src/JunimoGate.Mods/JunimoGate.Mods.csproj" />
  </ItemGroup>
</Project>
